<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/5/19
 * Time: 21:19
 * 开奖
 */
namespace  app\kai\controller;

use think\Controller;
use think\Db;
use think\Request;
use think\Cookie;
class Index extends Controller {
    protected  $table ="ma";

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(empty(cookie('mkey'))){
            return $this->index();
        }
    }

    public function index(){
          if($this->request->isPost()){
              $keytrue = Db::name($this->table)->order('id desc')->find();
              $key = input('post.key','','trim');

              if($keytrue['key'] != $key){
                  return json(['code'=>403,'msg'=>'兑奖码错误']);
               }
              if($keytrue['key'] == $key){
                  cookie('mkey',$keytrue['key']);
                  return json(['code'=>200,'msg'=>'兑奖码正确']);
              }
          }
        return $this->fetch();
    }

    public function info(){
        return $this->fetch();
    }
}